name: Sent Tweets News
on:
    schedule:
        - cron: '0 0 * * *'

jobs:
    sent:
        name: Sent News
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.0.0

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with: 
                python-version: 3.8

            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Run py
              env:
                DISCORD_CHANNEL_WEBHOOK: ${{ secrets.DISCORD_CHANNEL_WEBHOOK }}
                TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
                TWITTER_API_TOKEN: ${{ secrets.TWITTER_API_TOKEN}}
                TWITTER_SECRET_KEY: ${{ secrets.TWITTER_SECRET_KEY}}
                TWITTER_SECRET_TOKEN: ${{ secrets.TWITTER_SECRET_TOKEN}}
              run: python pushMLTweets.py $DISCORD_CHANNEL_WEBHOOK $TWITTER_API_KEY $TWITTER_API_TOKEN $TWITTER_SECRET_KEY $TWITTER_SECRET_TOKEN
